name: build

on:
  push:
    branches:
      - 'main'

jobs:
  nexus-repman-composer-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: cloudynes
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          cache-from: type=registry,ref=ghcr.io/cloudynes/php-base:cache
          cache-to: type=registry,ref=ghcr.io/cloudynes/php-base:cache
          context: .
          file: Dockerfile
          push: true
          tags: |
            ghcr.io/cloudynes/nexus-repository-composer:latest
